name: Deploy

on:
    pull_request:
        types: [closed]
        branches:
            - release

permissions:
    id-token: write  # Required for OIDC
    contents: read

jobs:
    build:
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: "dev"
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
                registry-url: 'https://registry.npmjs.org'
            # Ensure npm 11.5.1 or later is installed
            - run: npm install -g npm@latest
            - run: npm i
            - run: npm run build:prod
            - run: |
                  cd dist/ngx-material-auth
                  npm publish
